#!/bin/bash
#graspit compilation script
ROOT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
red='\033[0;31m'
blue='\033[0;34m'
none='\033[0m'

echo -e "${blue}Graspit is located in${none} $ROOT_PATH"
echo -e "${blue}Making build directory${none} $ROOT_PATH/build"
mkdir -p $ROOT_PATH/build
cd $ROOT_PATH/build

echo -e "${blue}Calling CMake!${none}"
cmake $ROOT_PATH

cores=$(nproc)
echo -e "${blue}Calling make with ${red}$cores${blue} cores${none}"
make -j $cores


echo -e "${blue}Returning to Graspit root${none}"
cd $ROOT_PATH
